Data cleaning using sklearn and Pandas 
- how to create in general dataframe
- import dataset from sklearn - Breast cancer 
- convert dataset to data frame
- standard scalar (x-u/σ )
- normalizer
- Do analysis using correct 

In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns

In [2]:
cd 

C:\Users\mouna


In [3]:
data = {'name': ['a','b','c','d','e','f',np.nan], 'Location': ['Hyd','Blr','Blr','Hyd','Bom','Bom',np.nan], 'Sales': [1000, 2000, 1000, 1500, '15%08', '13$03', np.nan], 'Profit': [10, 20, 30, 2E3, 'ER34', 40, 50]}

In [4]:
df = pd.DataFrame(data)

In [5]:
df.shape


(7, 4)

In [6]:
df

name Location  Sales  Profit
0    a      Hyd   1000      10
1    b      Blr   2000      20
2    c      Blr   1000      30
3    d      Hyd   1500  2000.0
4    e      Bom  15%08    ER34
5    f      Bom  13$03      40
6  NaN      NaN    NaN      50

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   name      6 non-null      object
 1   Location  6 non-null      object
 2   Sales     6 non-null      object
 3   Profit    7 non-null      object
dtypes: object(4)
memory usage: 352.0+ bytes


In [8]:
df['name'] = df['name'].fillna('a')
df['Location'] = df['Location'].fillna('Hyd')
df['Sales'] = df['Sales'].fillna('3000')
print (df)

  name Location  Sales  Profit
0    a      Hyd   1000      10
1    b      Blr   2000      20
2    c      Blr   1000      30
3    d      Hyd   1500  2000.0
4    e      Bom  15%08    ER34
5    f      Bom  13$03      40
6    a      Hyd   3000      50


In [9]:
from sklearn import datasets

In [10]:
health = datasets.load_breast_cancer

In [11]:
health

<function sklearn.datasets._base.load_breast_cancer(*, return_X_y=False, as_frame=False)>

In [12]:
data_h = health['data']

TypeError: 'function' object is not subscriptable

In [ ]:
data_df = pd.DataFrame(data_h)
print(data_df)

        0      1       2       3        4        5        6        7       8   \
0    17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010  0.14710  0.2419   
1    20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690  0.07017  0.1812   
2    19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740  0.12790  0.2069   
3    11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140  0.10520  0.2597   
4    20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800  0.10430  0.1809   
..     ...    ...     ...     ...      ...      ...      ...      ...     ...   
564  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390  0.13890  0.1726   
565  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400  0.09791  0.1752   
566  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251  0.05302  0.1590   
567  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140  0.15200  0.2397   
568   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000  0.00000  0.1587   

          9   ...      20  

In [ ]:
data_df.mean()

0      14.127292
1      19.289649
2      91.969033
3     654.889104
4       0.096360
5       0.104341
6       0.088799
7       0.048919
8       0.181162
9       0.062798
10      0.405172
11      1.216853
12      2.866059
13     40.337079
14      0.007041
15      0.025478
16      0.031894
17      0.011796
18      0.020542
19      0.003795
20     16.269190
21     25.677223
22    107.261213
23    880.583128
24      0.132369
25      0.254265
26      0.272188
27      0.114606
28      0.290076
29      0.083946
dtype: float64

In [ ]:
data_df.std()

0       3.524049
1       4.301036
2      24.298981
3     351.914129
4       0.014064
5       0.052813
6       0.079720
7       0.038803
8       0.027414
9       0.007060
10      0.277313
11      0.551648
12      2.021855
13     45.491006
14      0.003003
15      0.017908
16      0.030186
17      0.006170
18      0.008266
19      0.002646
20      4.833242
21      6.146258
22     33.602542
23    569.356993
24      0.022832
25      0.157336
26      0.208624
27      0.065732
28      0.061867
29      0.018061
dtype: float64

In [ ]:
from sklearn.preprocessing import StandardScaler
z_data = StandardScaler().fit_transform(data_df)

In [ ]:
z_data = pd.DataFrame(z_data)


In [ ]:
z_data.head()

0         1         2         3         4         5         6   \
0  1.097064 -2.073335  1.269934  0.984375  1.568466  3.283515  2.652874   
1  1.829821 -0.353632  1.685955  1.908708 -0.826962 -0.487072 -0.023846   
2  1.579888  0.456187  1.566503  1.558884  0.942210  1.052926  1.363478   
3 -0.768909  0.253732 -0.592687 -0.764464  3.283553  3.402909  1.915897   
4  1.750297 -1.151816  1.776573  1.826229  0.280372  0.539340  1.371011   

         7         8         9   ...        20        21        22        23  \
0  2.532475  2.217515  2.255747  ...  1.886690 -1.359293  2.303601  2.001237   
1  0.548144  0.001392 -0.868652  ...  1.805927 -0.369203  1.535126  1.890489   
2  2.037231  0.939685 -0.398008  ...  1.511870 -0.023974  1.347475  1.456285   
3  1.451707  2.867383  4.910919  ... -0.281464  0.133984 -0.249939 -0.550021   
4  1.428493 -0.009560 -0.562450  ...  1.298575 -1.466770  1.338539  1.220724   

         24        25        26        27        28        29  
0  1.307686  2.616665  2.109526  2.296076  2.750622  1.937015  
1 -0.375612 -0.430444 -0.146749  1.087084 -0.243890  0.281190  
2  0.527407  1.082932  0.854974  1.955000  1.152255  0.201391  
3  3.394275  3.893397  1.989588  2.175786  6.046041  4.935010  
4  0.220556 -0.313395  0.613179  0.729259 -0.868353 -0.397100  

[5 rows x 30 columns]

In [ ]:
z_data.mean()

0    -3.162867e-15
1    -6.530609e-15
2    -7.078891e-16
3    -8.799835e-16
4     6.132177e-15
5    -1.120369e-15
6    -4.421380e-16
7     9.732500e-16
8    -1.971670e-15
9    -1.453631e-15
10   -9.076415e-16
11   -8.853492e-16
12    1.773674e-15
13   -8.291551e-16
14   -7.541809e-16
15   -3.921877e-16
16    7.917900e-16
17   -2.739461e-16
18   -3.108234e-16
19   -3.366766e-16
20   -2.333224e-15
21    1.763674e-15
22   -1.198026e-15
23    5.049661e-16
24   -5.213170e-15
25   -2.174788e-15
26    6.856456e-16
27   -1.412656e-16
28   -2.289567e-15
29    2.575171e-15
dtype: float64

In [ ]:
z_data.std()

0     1.00088
1     1.00088
2     1.00088
3     1.00088
4     1.00088
5     1.00088
6     1.00088
7     1.00088
8     1.00088
9     1.00088
10    1.00088
11    1.00088
12    1.00088
13    1.00088
14    1.00088
15    1.00088
16    1.00088
17    1.00088
18    1.00088
19    1.00088
20    1.00088
21    1.00088
22    1.00088
23    1.00088
24    1.00088
25    1.00088
26    1.00088
27    1.00088
28    1.00088
29    1.00088
dtype: float64

In [ ]:
from sklearn.preprocessing import Normalizer
n = Normalizer().fit(data_df)
da_n = n.transform(data_df)

In [ ]:
n 

Normalizer()

In [ ]:
da_n

array([[7.92541486e-03, 4.57286305e-03, 5.40989964e-02, ...,
        1.16920795e-04, 2.02695018e-04, 5.23808686e-05],
       [8.66575595e-03, 7.48616836e-03, 5.59882822e-02, ...,
        7.83583182e-05, 1.15852352e-04, 3.75024596e-05],
       [9.36668268e-03, 1.01087865e-02, 6.18419883e-02, ...,
        1.15596947e-04, 1.71873157e-04, 4.16624718e-05],
       ...,
       [1.16438847e-02, 1.96964025e-02, 7.59658259e-02, ...,
        9.94640269e-05, 1.55579134e-04, 5.48525170e-05],
       [9.23020523e-03, 1.31418408e-02, 6.27743569e-02, ...,
        1.18738077e-04, 1.83125480e-04, 5.55604587e-05],
       [2.31098880e-02, 7.30820427e-02, 1.42709515e-01, ...,
        0.00000000e+00, 8.55006294e-04, 2.09626935e-04]])

In [ ]:
data_n = pd.DataFrame(da_n)

In [ ]:
data_n.head()

0         1         2         3         4         5         6   \
0  0.007925  0.004573  0.054099  0.440986  0.000052  0.000122  0.000132   
1  0.008666  0.007486  0.055988  0.558619  0.000036  0.000033  0.000037   
2  0.009367  0.010109  0.061842  0.572276  0.000052  0.000076  0.000094   
3  0.016325  0.029133  0.110899  0.551922  0.000204  0.000406  0.000345   
4  0.009883  0.006985  0.065808  0.631774  0.000049  0.000065  0.000096   

         7         8         9   ...        20        21        22        23  \
0  0.000065  0.000107  0.000035  ...  0.011181  0.007635  0.081325  0.889462   
1  0.000030  0.000076  0.000024  ...  0.010528  0.009862  0.066899  0.824026   
2  0.000061  0.000098  0.000029  ...  0.011212  0.012145  0.072545  0.812984   
3  0.000150  0.000371  0.000139  ...  0.021314  0.037881  0.141333  0.811515   
4  0.000051  0.000088  0.000029  ...  0.010979  0.008120  0.074137  0.767189   

         24        25        26        27        28        29  
0  0.000071  0.000293  0.000314  0.000117  0.000203  0.000052  
1  0.000052  0.000079  0.000102  0.000078  0.000116  0.000038  
2  0.000069  0.000202  0.000214  0.000116  0.000172  0.000042  
3  0.000300  0.001238  0.000982  0.000368  0.000949  0.000247  
4  0.000067  0.000100  0.000195  0.000079  0.000115  0.000037  

[5 rows x 30 columns]

In [ ]:
data_n.mean()

0     0.014843
1     0.022010
2     0.096006
3     0.605084
4     0.000113
5     0.000110
6     0.000079
7     0.000042
8     0.000212
9     0.000076
10    0.000397
11    0.001493
12    0.002798
13    0.033316
14    0.000009
15    0.000029
16    0.000036
17    0.000013
18    0.000025
19    0.000005
20    0.016745
21    0.029162
22    0.109652
23    0.777287
24    0.000155
25    0.000262
26    0.000261
27    0.000108
28    0.000335
29    0.000099
dtype: float64

In [ ]:
data_n.std()

0     0.004011
1     0.011077
2     0.024912
3     0.047241
4     0.000059
5     0.000065
6     0.000073
7     0.000023
8     0.000111
9     0.000043
10    0.000208
11    0.001218
12    0.001422
13    0.015373
14    0.000008
15    0.000029
16    0.000056
17    0.000010
18    0.000019
19    0.000005
20    0.004009
21    0.014452
22    0.025127
23    0.037726
24    0.000083
25    0.000175
26    0.000236
27    0.000053
28    0.000170
29    0.000056
dtype: float64

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca_f = pca.fit(data_df)
dr_df = pca_f.transform(data_df)
print(pca.explained_variance_ratio_)
print(dr_df)

[0.98204467 0.01617649]
[[1160.1425737  -293.91754364]
 [1269.12244319   15.63018184]
 [ 995.79388896   39.15674324]
 ...
 [ 314.50175618   47.55352518]
 [1124.85811531   34.12922497]
 [-771.52762188  -88.64310636]]


In [ ]:
dr_df

array([[1160.1425737 , -293.91754364],
       [1269.12244319,   15.63018184],
       [ 995.79388896,   39.15674324],
       ...,
       [ 314.50175618,   47.55352518],
       [1124.85811531,   34.12922497],
       [-771.52762188,  -88.64310636]])

In [ ]:
df

name Location  Sales  Profit
0    a      Hyd   1000      10
1    b      Blr   2000      20
2    c      Blr   1000      30
3    d      Hyd   1500  2000.0
4    e      Bom  15%08    ER34
5    f      Bom  13$03      40
6    a      Hyd   3000      50

In [ ]:
#Encoding - To convert any Alphabetical data into numbers
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['name'] = le.fit_transform(df['name'])
print(df)


   name Location  Sales  Profit
0     0      Hyd   1000      10
1     1      Blr   2000      20
2     2      Blr   1000      30
3     3      Hyd   1500  2000.0
4     4      Bom  15%08    ER34
5     5      Bom  13$03      40
6     0      Hyd   3000      50


In [ ]:
#loc = LabelEncoder()
#df['Location'] = le.fit_transform(df['Location'])
#print(df)

In [ ]:
df = df.dropna()

In [ ]:
df

name Location  Sales  Profit
0     0      Hyd   1000      10
1     1      Blr   2000      20
2     2      Blr   1000      30
3     3      Hyd   1500  2000.0
4     4      Bom  15%08    ER34
5     5      Bom  13$03      40
6     0      Hyd   3000      50

In [ ]:
#one -hot encoding - parametric models
#label encodeing - non parametric  model

#to remove heteroskedasticity we use one hot encoding



In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   name      7 non-null      int32 
 1   Location  7 non-null      object
 2   Sales     7 non-null      object
 3   Profit    7 non-null      object
dtypes: int32(1), object(3)
memory usage: 324.0+ bytes


In [ ]:
lb_loc = pd.get_dummies(df['Location'])
print(lb_loc)



   Blr  Bom  Hyd
0    0    0    1
1    1    0    0
2    1    0    0
3    0    0    1
4    0    1    0
5    0    1    0
6    0    0    1


In [ ]:
df1 = pd.concat([df,lb_loc], axis = 1)

In [ ]:
df1

name Location  Sales  Profit  Blr  Bom  Hyd
0     0      Hyd   1000      10    0    0    1
1     1      Blr   2000      20    1    0    0
2     2      Blr   1000      30    1    0    0
3     3      Hyd   1500  2000.0    0    0    1
4     4      Bom  15%08    ER34    0    1    0
5     5      Bom  13$03      40    0    1    0
6     0      Hyd   3000      50    0    0    1

In [ ]:
del df1['Location']

In [ ]:
df1

name  Sales  Profit  Blr  Bom  Hyd
0     0   1000      10    0    0    1
1     1   2000      20    1    0    0
2     2   1000      30    1    0    0
3     3   1500  2000.0    0    0    1
4     4  15%08    ER34    0    1    0
5     5  13$03      40    0    1    0
6     0   3000      50    0    0    1